# Data Splitting (Stratified Holdout Strategy with Validation Set)

## Stratification is based on the target variable

### **Import Dependecies**

In [1]:
import pandas as pd
from pathlib import Path
# from sklearn.model_selection import train_test_split
from src.utils.data_split.functions import (
    split_data,
    create_y_class_report,
    export_split_data_to_csv,
    binarize_readmitted
)

### **Import the dataset:**

In [2]:
# initializing the paths
PATH = Path("../../data/source/diabetic_data.csv")
# used for exporting the splitted datasets
SPLITTED_PATH = Path("../../data/interim/split_stratified")
 #reading the datasets
df = pd.read_csv(PATH)

**Binarize Target Variable (readmission to hospital):**

- 'No readmission' is mapped to 0,
- '>30' days is mapped to 1,
- and '<30' days is mapped to 1.

In [3]:
df = binarize_readmitted(df)
df[['encounter_id', 'readmitted']].head()

   encounter_id  readmitted
0       2278392           0
1        149190           1
2         64410           0
3        500364           0
4         16680           0

### **Applying the  splitting functions**

**Applying the data split function**

In [4]:
X_train_for_cv, X_train_mini, X_val, X_test, \
    y_train_for_cv, y_train_mini, y_val, y_test = split_data(df,
                                                      test_size_step_1= 0.2,
                                                      test_size_step_2= 0.25)

Data split report
-----
Original data shape: (101766, 50)
X_train shape:      (81412, 49) | y_train shape:      (81412,)
X_train_mini shape: (61059, 49) | y_train_mini shape: (61059,)
X_val shape:        (20353, 49) | y_val shape:        (20353,)
X_test shape:       (20354, 49) | y_test shape:       (20354,)
-----
Train pool rows: 81412 (80.00% of full data)
Train rows:      61059 (60.00% of full data)
Validation rows: 20353 (20.00% of full data)
Test rows:       20354 (20.00% of full data)

**Brief report of target class counts and percentages for each dataset**:

In [5]:
y_class_report = create_y_class_report(y_train_mini, y_val, y_test)
y_class_report

      Dataset  Class  Count  Percentage  Total Rows
0       Train      1  28141       46.09       61059
1       Train      0  32918       53.91       61059
2  Validation      1   9380       46.09       20353
3  Validation      0  10973       53.91       20353
4        Test      1   9381       46.09       20354
5        Test      0  10973       53.91       20354

**Export datasets to ../data/interim/splitted/**

In [6]:
split_file_paths = export_split_data_to_csv(
    X_train_for_cv, X_train_mini, X_val, X_test,
    y_train_for_cv, y_train_mini, y_val, y_test,
    output_folder= SPLITTED_PATH
)

Exported 8 split CSV files to: ../../data/interim/split_stratified
- X_train_for_cv: ../../data/interim/split_stratified/X_train_for_cv.csv
- X_train_mini: ../../data/interim/split_stratified/X_train_mini.csv
- X_val: ../../data/interim/split_stratified/X_val.csv
- X_test: ../../data/interim/split_stratified/X_test.csv
- y_train_for_cv: ../../data/interim/split_stratified/y_train_for_cv.csv
- y_train_mini: ../../data/interim/split_stratified/y_train_mini.csv
- y_val: ../../data/interim/split_stratified/y_val.csv
- y_test: ../../data/interim/split_stratified/y_test.csv