# Data Splitting (Group Shuffle Split by group (Patient number))

#### **Import Dependecies**

In [1]:
import pandas as pd
from pathlib import Path
# from sklearn.model_selection import train_test_split, GroupShuffleSplit
from src.utils.data_split.functions import (split_data_by_patient,
                                            create_y_class_report,
                                            export_split_data_to_csv,
                                            binarize_readmitted
                                            )

#### **Import the dataset:**

In [2]:
# initializing the paths
PATH = Path("../../data/source/diabetic_data.csv")
# used for exporting the splitted datasets
SPLITTED_PATH = Path("../../data/interim/split_groupshuffle")
 #reading the datasets
df = pd.read_csv(PATH)
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

**Binarize Target Variable (readmission to hospital):**

- 'No readmission' is mapped to 0,
- '>30' days is mapped to 1,
- and '<30' days is mapped to 1.

In [3]:
df = binarize_readmitted(df)
df[['encounter_id', 'readmitted']].head()

   encounter_id  readmitted
0       2278392           0
1        149190           1
2         64410           0
3        500364           0
4         16680           0

### Applying the custom functions for splitting data by group (patient number)

**Applying the data split function**

In [4]:
X_train_for_cv, X_train_mini, X_val, X_test, \
    y_train_for_cv, y_train_mini, y_val, y_test = \
    split_data_by_patient(df,
                          test_size_step_1= 0.20,
                          test_size_step_2= 0.25)

Patient-grouped data split report
-----
Original data shape: (101766, 50)
X_train shape:      (81488, 48) | y_train shape:      (81488,)
X_train_mini shape: (61211, 48) | y_train_mini shape: (61211,)
X_val shape:        (20277, 48) | y_val shape:        (20277,)
X_test shape:       (20278, 48) | y_test shape:       (20278,)
-----
Train pool rows: 81488 (80.07% of full data)
Train rows:      61211 (60.15% of full data)
Validation rows: 20277 (19.93% of full data)
Test rows:       20278 (19.93% of full data)
-----
Train pool patients: 57214
Train patients:      42910
Validation patients: 14304
Test patients:       14304
-----
Train/validation patient overlap: 0
Train/test patient overlap:       0
Validation/test patient overlap:  0

**Brief report of target class counts and percentages for each dataset**:

In [5]:
y_class_report = create_y_class_report(y_train_mini, y_val, y_test)
y_class_report

      Dataset  Class  Count  Percentage  Total Rows
0       Train      1  28296       46.23       61211
1       Train      0  32915       53.77       61211
2  Validation      1   9272       45.73       20277
3  Validation      0  11005       54.27       20277
4        Test      1   9334       46.03       20278
5        Test      0  10944       53.97       20278

**Export datasets to ../data/interim/folder_name/**

In [6]:
split_file_paths = export_split_data_to_csv(
    X_train_for_cv, X_train_mini, X_val, X_test,
    y_train_for_cv, y_train_mini, y_val, y_test,
    output_folder= SPLITTED_PATH
)

Exported 8 split CSV files to: ../../data/interim/split_groupshuffle
- X_train_for_cv: ../../data/interim/split_groupshuffle/X_train_for_cv.csv
- X_train_mini: ../../data/interim/split_groupshuffle/X_train_mini.csv
- X_val: ../../data/interim/split_groupshuffle/X_val.csv
- X_test: ../../data/interim/split_groupshuffle/X_test.csv
- y_train_for_cv: ../../data/interim/split_groupshuffle/y_train_for_cv.csv
- y_train_mini: ../../data/interim/split_groupshuffle/y_train_mini.csv
- y_val: ../../data/interim/split_groupshuffle/y_val.csv
- y_test: ../../data/interim/split_groupshuffle/y_test.csv