# Data Splitting (Group Shuffle Split by group (Patient number))

#### **Import Dependecies**

In [1]:
import pandas as pd
from pathlib import Path
# from sklearn.model_selection import train_test_split, GroupShuffleSplit
from src.utils.data_split.functions import (split_data_by_patient,
                                            create_y_class_report,
                                            export_split_data_to_csv)

#### **Import the dataset:**

In [2]:
# initializing the paths
PATH = Path("../../data/source/diabetic_data.csv")
# used for exporting the splitted datasets
SPLITTED_PATH = Path("../../data/interim/split_groupshuffle")
 #reading the datasets
df = pd.read_csv(PATH)
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

### Applying the custom functions for splitting data by group (patient number)

**Applying the data split function**

In [3]:
X_train_mini, X_val, X_test, y_train_mini, y_val, y_test = \
    split_data_by_patient(df)

Patient-grouped data split report
-----
Original data shape: (101766, 50)
X_train_mini shape: (65256, 48) | y_train_mini shape: (65256,)
X_val shape:        (16232, 48) | y_val shape:        (16232,)
X_test shape:       (20278, 48) | y_test shape:       (20278,)
-----
Train rows:      65256 (64.12% of full data)
Validation rows: 16232 (15.95% of full data)
Test rows:       20278 (19.93% of full data)
-----
Train patients:      45771
Validation patients: 11443
Test patients:       14304
-----
Train/validation patient overlap: 0
Train/test patient overlap:       0
Validation/test patient overlap:  0

**Brief report of target class counts and percentages for each dataset**:

In [4]:
y_class_report = create_y_class_report(y_train_mini, y_val, y_test)
y_class_report

      Dataset Class  Count  Percentage  Total Rows
0       Train    NO  35144       53.86       65256
1       Train   >30  22843       35.01       65256
2       Train   <30   7269       11.14       65256
3  Validation    NO   8776       54.07       16232
4  Validation   >30   5660       34.87       16232
5  Validation   <30   1796       11.06       16232
6        Test    NO  10944       53.97       20278
7        Test   >30   7042       34.73       20278
8        Test   <30   2292       11.30       20278

**Export datasets to ../data/interim/folder_name/**

In [5]:
split_file_paths = export_split_data_to_csv(
    X_train_mini, X_val, X_test,
    y_train_mini, y_val, y_test,
    output_folder= SPLITTED_PATH
)

Exported 6 split CSV files to: ../../data/interim/split_groupshuffle
- X_train_mini: ../../data/interim/split_groupshuffle/X_train_mini.csv
- X_val: ../../data/interim/split_groupshuffle/X_val.csv
- X_test: ../../data/interim/split_groupshuffle/X_test.csv
- y_train_mini: ../../data/interim/split_groupshuffle/y_train_mini.csv
- y_val: ../../data/interim/split_groupshuffle/y_val.csv
- y_test: ../../data/interim/split_groupshuffle/y_test.csv